import { BedrockRuntimeClient, InvokeModelCommand } from '@aws-sdk/client-bedrock-runtime'

const REGION = import.meta.env.VITE_AWS_REGION || 'ap-south-1'
const ACCESS_KEY_ID = import.meta.env.VITE_AWS_ACCESS_KEY_ID
const SECRET_ACCESS_KEY = import.meta.env.VITE_AWS_SECRET_ACCESS_KEY
const MODEL_ID = 'anthropic.claude-3-sonnet-20240229-v1:0' // Use Claude instead of Nova Pro

console.log('🔧 Bedrock Floating Chat Config:', {
  region: REGION,
  modelId: MODEL_ID,
  hasAccessKey: !!ACCESS_KEY_ID,
  hasSecretKey: !!SECRET_ACCESS_KEY
})

const client = new BedrockRuntimeClient({
  region: REGION,
  credentials: {
    accessKeyId: ACCESS_KEY_ID!,
    secretAccessKey: SECRET_ACCESS_KEY!,
  },
})

export interface BedrockFloatingChatResponse {
  message: string
  confidence: number
}

export async function callBedrockFloatingChat(prompt: string): Promise<BedrockFloatingChatResponse> {
  console.log('🔍 Calling Bedrock Claude for business guidance:', prompt)
  console.log('🔍 Using model:', MODEL_ID)
  console.log('🔍 Region:', REGION)
  
  try {
    const systemPrompt = `You are an AI business assistant for LUX Industries Limited, India's leading innerwear and hosiery brand.

    COMPANY BACKGROUND:
    - Founded in 1995, LUX Industries is India's leading innerwear brand with 15% organized sector market share
    - Specializes in premium innerwear, hosiery, and lifestyle garments
    - Products include innerwear, socks, t-shirts, and lifestyle clothing under brands like Lux Venus, Lyra, Lux Inferno, Lux Nitro, Lux Cozi, ONN, One8, Lux Classic, GenX, Lux Amore, Lux Cott's Wool, Lux Parker, and Lux Mozze
    - Manufacturing capacity: 1.2 million garments per day across 9 facilities
    - Distribution: 2000+ distributors and over 0.5 million retailers
    - Global presence: Exports to 46+ countries with 'Star Export House' status
    - Online presence: Available on Flipkart, Amazon, Myntra, and Ajio

    BRANDS:
    - Lux Venus (Premium innerwear)
    - Lyra (Fashion innerwear)
    - Lux Inferno (Sports innerwear)
    - Lux Nitro (Performance wear)
    - Lux Cozi (Comfort wear)
    - ONN, One8, Lux Classic, GenX, Lux Amore, Lux Cott's Wool, Lux Parker, Lux Mozze

    YOUR ROLE:
    - Provide helpful business guidance and customer support
    - Answer questions about LUX Industries products, brands, and services
    - Offer insights on innerwear trends, fashion, and business strategies
    - Be professional, friendly, and knowledgeable
    - Keep responses concise but informative

    RESPONSE STYLE:
    - Professional yet approachable
    - Focus on LUX Industries context and innerwear business
    - Provide actionable insights when possible
    - Be helpful and informative
    - Use proper formatting with bullet points and clear structure`

    const input = {
      modelId: MODEL_ID,
      contentType: 'application/json',
      accept: 'application/json',
      body: JSON.stringify({
        prompt: `${systemPrompt}\n\nUser question: ${prompt}\n\nPlease provide a helpful business-focused response.`,
        max_tokens_to_sample: 1000,
        temperature: 0.1,
      }),
    }

    console.log('📤 Sending request to Bedrock:', input)

    const command = new InvokeModelCommand(input)
    const response = await client.send(command)
    const responseBody = await response.body.transformToString()
    const parsedResponse = JSON.parse(responseBody)
    
    console.log('✅ Bedrock response:', parsedResponse)
    
    // Extract the completion text from Claude response
    const completion = parsedResponse.completion || ''
    console.log('✅ Bedrock generated text:', completion)

    if (!completion) {
      console.warn('⚠️ No completion text found in response')
      throw new Error('No text generated by Bedrock')
    }

    return {
      message: completion,
      confidence: 0.9
    }

  } catch (error) {
    console.error('❌ Bedrock API Error:', error)
    
    // Return more specific fallback responses based on the question
    const lowerPrompt = prompt.toLowerCase()
    
    if (lowerPrompt.includes('product') || lowerPrompt.includes('brand')) {
      return {
        message: "LUX Industries offers a wide range of premium innerwear and hosiery products under brands like Lux Venus (premium), Lyra (fashion), Lux Inferno (sports), Lux Nitro (performance), and Lux Cozi (comfort). Our products include innerwear, socks, t-shirts, and lifestyle clothing available through 2000+ distributors and online on Flipkart, Amazon, Myntra, and Ajio.",
        confidence: 0.7
      }
    } else if (lowerPrompt.includes('business') || lowerPrompt.includes('company')) {
      return {
        message: "LUX Industries Limited, founded in 1995, is India's leading innerwear brand with 15% organized sector market share. We manufacture 1.2 million garments per day across 9 facilities, distribute through 2000+ distributors to over 0.5 million retailers, and export to 46+ countries with 'Star Export House' status.",
        confidence: 0.7
      }
    } else if (lowerPrompt.includes('contact') || lowerPrompt.includes('support')) {
      return {
        message: "For business inquiries, product information, or customer support, you can reach LUX Industries through our extensive network of 2000+ distributors and 0.5 million retailers across India. We also have a strong online presence on major e-commerce platforms.",
        confidence: 0.7
      }
    } else {
      return {
        message: "Thank you for your question about LUX Industries! I'm here to help with any business inquiries, product information, or guidance you might need. How can I assist you today?",
        confidence: 0.7
      }
    }
  }
} 