const GEMINI_API_KEY = import.meta.env.VITE_GEMINI_API_KEY
const GEMINI_API_URL = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent'

export interface GeminiResponse {
  message: string
  confidence: number
}

export async function callGemini(prompt: string): Promise<GeminiResponse> {
  console.log('🔍 Calling Gemini API for business guidance:', prompt)
  
  try {
    const systemPrompt = `You are an AI business assistant for LUX Industries Limited, India's leading innerwear and hosiery brand.

    COMPANY BACKGROUND:
    - Founded in 1995, LUX Industries is India's leading innerwear brand with 15% organized sector market share
    - Specializes in premium innerwear, hosiery, and lifestyle garments
    - Products include innerwear, socks, t-shirts, and lifestyle clothing under brands like Lux Venus, Lyra, Lux Inferno, Lux Nitro, Lux Cozi, ONN, One8, Lux Classic, GenX, Lux Amore, Lux Cott's Wool, Lux Parker, and Lux Mozze
    - Manufacturing capacity: 1.2 million garments per day across 9 facilities
    - Distribution: 2000+ distributors and over 0.5 million retailers
    - Global presence: Exports to 46+ countries with 'Star Export House' status
    - Online presence: Available on Flipkart, Amazon, Myntra, and Ajio

    BRANDS:
    - Lux Venus (Premium innerwear)
    - Lyra (Fashion innerwear)
    - Lux Inferno (Sports innerwear)
    - Lux Nitro (Performance wear)
    - Lux Cozi (Comfort wear)
    - ONN, One8, Lux Classic, GenX, Lux Amore, Lux Cott's Wool, Lux Parker, Lux Mozze

    YOUR ROLE:
    - Provide helpful business guidance and customer support
    - Answer questions about LUX Industries products, brands, and services
    - Offer insights on innerwear trends, fashion, and business strategies
    - Be professional, friendly, and knowledgeable
    - Keep responses concise but informative

    RESPONSE STYLE:
    - Professional yet approachable
    - Focus on LUX Industries context and innerwear business
    - Provide actionable insights when possible
    - Be helpful and informative
    - Use proper formatting with bullet points and clear structure`

    const response = await fetch(`${GEMINI_API_URL}?key=${GEMINI_API_KEY}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [
          {
            parts: [
              {
                text: `${systemPrompt}\n\nUser question: ${prompt}\n\nPlease provide a helpful business-focused response.`
              }
            ]
          }
        ]
      })
    })

    if (!response.ok) {
      throw new Error(`Gemini API error: ${response.status} ${response.statusText}`)
    }

    const data = await response.json()
    console.log('✅ Gemini response:', data)

    // Extract the generated text from Gemini response
    const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text || ''
    console.log('✅ Gemini generated text:', generatedText)

    if (!generatedText) {
      throw new Error('No text generated by Gemini')
    }

    return {
      message: generatedText,
      confidence: 0.9
    }

  } catch (error) {
    console.error('❌ Gemini API Error:', error)
    
    // Return fallback response
    return {
      message: "Thank you for your question about LUX Industries! I'm here to help with any business inquiries, product information, or guidance you might need. How can I assist you today?",
      confidence: 0.7
    }
  }
} 
